### ISSUE TITLE
Handbook: cd (change directory) instruction missing from /luminactbt.html#getting-the-source-code

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina-docs#14]
https://lumina-desktop.org/handbook/luminactbt.html#getting-the-source-code

```
git clone git://github.com/trueos/lumina.git
git pull
```

That sequence of commands does not work. I think there's a line missing, a command to be performed after cloning: 

`cd lumina`

**Comment by q5sys** [comment]
Technically you would not need to type `git pull` after you cloned the repo because it's already up to date.  Running `git pull` will catch you up as time passes by and your local copy is no longer synced with the master source repo.
This is explained in the next paragraph. I've removed the extraneous `git pull`
https://github.com/trueos/lumina-docs/commit/45d8f463fe8bbbbbee0f0f1cf8870e9437792837
